/**
* @File Name          : SHF_Record_Outcome_API_Service.cls
* @Description        : API to run Record Outcome API After Hunter Check for Primary Applicant.
* @Author             : Akshi Sharma 
*==============================================================================
* Ver         Date                     Author                 Modification
*==============================================================================
* 1.0         14-08-2025               Akshi Sharma           Initial Version
*/
public class SHF_Record_Outcome_API_Service {

}